import turtle 
radius1 = float(input("Enter the radius of the first circle: "))
radius2 = float(input("Enter the radius of the second cirle: "))
radius3 = float(input("Enter the radius of the third circle: "))
turtle.speed(0)
turtle.hideturtle()
turtle.bgcolor("black")
def Snowman(x, y, radius1, radius2, radius3):
  turtle.goto(x, y)
  turtle.color("light blue")
  turtle.begin_fill()
  turtle.circle(radius1)
  turtle.end_fill()
  turtle.up()
  turtle.right(90)
  turtle.forward(radius2 * 2)
  turtle.left(90)
  turtle.begin_fill()
  turtle.circle(radius2)
  turtle.end_fill()
  turtle.up()
  turtle.right(90)
  turtle.forward(radius3 * 2)
  turtle.left(90)  
  turtle.begin_fill()
  turtle.circle(radius3)
  turtle.end_fill()
  turtle.color("blue")
  turtle.left(90)
  turtle.forward(radius3*2+radius2*2+radius1)
  turtle.left(-90)
  turtle.forward(radius1/2)
  turtle.begin_fill()
  turtle.circle(radius1/6)
  turtle.end_fill()
  turtle.left(180)
  turtle.forward(radius1)
  turtle.right(180)
  turtle.begin_fill()
  turtle.circle(radius1/6)
  turtle.end_fill()
  turtle.forward(radius1/2)
  turtle.right(90)
  turtle.color("orange")
  turtle.begin_fill()
  turtle.forward(radius1/2)
  turtle.left(120)
  turtle.forward(radius1/2)
  turtle.left(120)

      